### ISSUE TITLE
JSON - RPC Client Exception 

### ISSUE THREAD

**Issue by florin-systouch** [odoo-java/odoo-java-api#27]
On rencontre une exception au moment du récupérer le contenu byte[] d'un rapport en format , qweb-pdf  à partir du serveur ODOO
La connexion initiale de la session se passe bien , le report en question il se trouve dans le cache retourné : reportListCache.

Par contre au moment de l'appel de cette ligne de la lib

**Object[] result = session.call_report_jsonrpc(getReportModel(), getReportMethod(), reportParams);** 

On sort directement dans l'exception 
 _at com.googlecode.jsonrpc4j.DefaultExceptionResolver.createJsonRpcClientException(DefaultExceptionResolver.java:53) ~[jsonrpc4j-1.6.jar!/:?]
        at com.googlecode.jsonrpc4j.DefaultExceptionResolver.resolveException(DefaultExceptionResolver.java:32) ~[jsonrpc4j-1.6.jar!/:?]
        at com.googlecode.jsonrpc4j.JsonRpcClient.handleErrorResponse(JsonRpcClient.java:272) ~[jsonrpc4j-1.6.jar!/:?]
        at com.googlecode.jsonrpc4j.JsonRpcClient.readResponse(JsonRpcClient.java:196) ~[jsonrpc4j-1.6.jar!/:?]
        at com.googlecode.jsonrpc4j.JsonRpcClient.readResponse(JsonRpcClient.java:539) ~[jsonrpc4j-1.6.jar!/:?]
        at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:143) ~[jsonrpc4j-1.6.jar!/:?]
        at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:113) ~[jsonrpc4j-1.6.jar!/:?]
        at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:175) ~[jsonrpc4j-1.6.jar!/:?]
        at com.odoojava.api.Session.call_report_jsonrpc(Session.java:292) ~[odoo-java-api-3.3.2.jar!/:?]
        at com.odoojava.api.ReportAdapter.getPDFReportAsByte(ReportAdapter.java:127) ~[odoo-java-api-3.3.2.jar!/:?]_

Le URL généré par la session est le suivant : **https://srv02.hopodoo.com:443/jsonrpc**

**Comment by florin-systouch** [comment]
![image](https://github.com/odoo-java/odoo-java-api/assets/143516467/e15edc12-29cf-4fff-aba2-ac48420f1af4)

**Comment by flotho** [comment]
thanks for the report,
Could you confirm that you are using this lib 
![image](https://github.com/odoo-java/odoo-java-api/assets/1043935/5299d48d-26c4-46e9-81c4-1c7ef17b8306)

additionnaly, could you provide more information. Is it a specific report, do you use a specific user with or without API Key ?
Thanks for giving feedback.
Regards

**Comment by flotho** [comment]
For example ou unit tests succeed in printing "account.report_invoice" whatever the id .

**Comment by florin-systouch** [comment]
Hello

I can confirme I use the correct LIB.





*#Generated by Maven#Tue Nov 14 14:13:45 CET
2023groupId=com.odoojavaartifactId=odoo-java-apiversion=3.3.2*

Is authentification by user name & password no API KEY
The autentification phase is going OK i get an userID from ODOOO.
The folowing informatiosn are used and can help you to identify the problem
maybe. If not I will be disponible for more informations.















*Prepare Invoice NO :42255 session.initSession - URL srv02.hopodoo.com
<http://srv02.hopodoo.com> session.initSession - PORT
443 session.initSession - DB universkin_v2 session.initSession - LOGIN
***@***.*** ***@***.***> session.initSession - MDP
7wWR{p2K  getReportName() account.report_invoice getReportID()
183 getReportMethod(); render reportAdapter.getReportType()qweb-pdf
 String reportModel = "ir.actions.report"; String reportMethod = "render";*

Thanks for helping us.

**Comment by flotho** [comment]
hum....
ok, I remember something
you also have to use a patch on your ODoo server because render method is no more available

**Comment by flotho** [comment]
Did you try this : https://github.com/odoo-java/odoo-java-api/issues/17#issuecomment-946575378
